### ISSUE TITLE
[Question] Support for array of audiences / issuers?

### ISSUE THREAD

**Issue by bneigher** [nearform/fastify-auth0-verify#10]
Hey fastify / nearform team.  Just gave this a try from my custom jwt setup and it works great.

The only thing missing is the ability to have multiple issuers or audiences in the verification process.  It this open for implementation? Is in place with fastify-jwt

Use case should be clear, but for example I have an API with this verification logic in it, but I have several auth0 clients that speak to it.  Or I have an admin api that I use for impersonation that forces the client_id as the audience.

My previous setup was:

```
const FastifyJWT = require("fastify-jwt");
const JwksRsa = require("./util/jwks.js");

...
fastify.register(FastifyJWT, {
    secret: JwksRsa({
      cache: true,
      rateLimit: false,
      jwksRequestsPerMinute: 100, // Default value
      cacheMaxEntries: 50, // Default value
      cacheMaxAge: Ms("10h"), // Default value
      jwksUri: Config.auth.jwksUri
    }),
    verify: {
      algorithms: ["RS256"],
      audience: Config.auth.audience,
      issuer: [`https://${Config.auth.domain}/`, `https://${Config.auth.domain2}/`]
    },
    decode: {
      complete: true
    }
});
```

And now:
```
const FastifyAuth0Verify = require("fastify-auth0-verify")

...
fastify.register(FastifyAuth0Verify, {
    secret: Config.auth.clientSecret,
    domain: `https://${Config.auth.domain}/`,
    audience: Config.auth.audience,
    secretsTtl: 10 * 60 * 60 * 1000 // 10hr
})
```
So the only real feature missing here is the array of issuers and audiences.

**Comment by admataz** [comment]
Hi @bneigher  - I've created a PR that makes the changes you mention - can you test the version in the PR against your app? 

see: https://github.com/nearform/fastify-auth0-verify/pull/12
