### ISSUE TITLE
Login flow

### ISSUE THREAD

**Issue by Dannybrown2710** [nearform/fastify-auth0-verify#143]
Hi Team,
Thank you for your contribution on creating the plugin for Auth0.
I was able to add plugin to verify but is there any method to implement custom login using the plugin?

**Comment by simoneb** [comment]
@Dannybrown2710 what do you mean?

**Comment by Dannybrown2710** [comment]
How to use all the auth0 methods such as getProfile and authorize which are used to login or sign-up to database based connection?

**Comment by simoneb** [comment]
The purpose of this plugin is to verify JWT tokens generated by Auth0. To do additional operations you'll need to use the Auth0 SDK. In fact, this plugin does not use any Auth0 SDK, so it wouldn't make much sense to expose those operations as we would be duplicating logic that's already in the official SDK.
