### ISSUE TITLE
Mocking fastify-auth0-verify with jest

### ISSUE THREAD

**Issue by igorshmukler** [nearform/fastify-auth0-verify#164]
Hello,

I am unsure how this should be filed. I would like to suggest something for consideration.
In my opinion, It would be awesome if README.md or another document included jest mocking examples. There are mocks included with the sources, yet no good examples for developers writing tests for routes utilizing your library and `authenticate`.

Thank you.

**Comment by simoneb** [comment]
As described in the readme the main thing that this plugin does is register a [decorator](https://www.fastify.io/docs/latest/Decorators/) called `authenticate`. Hence, mocking this plugin doesn't require any particular pattern outside of mocking a function on the server object.

If you're testing routes which in one of their hooks (e.g. `preValidation`) expects that decorator, all you need to do is provide one. For example:

```js
const server = fastify()

const mockAuthenticate = jest.fn()
// configure the behavior of your mock authenticate decorator

fastify.decorate('authenticate', mockAuthenticate)

fastify.register(<your route module>)

fastify.inject(<url of your route>)

// your expectations
```

**Comment by igorshmukler** [comment]
Thank you. Appreciate you taking the time to answer, especially on a weekend. Your suggestion I am sure will work. 

The issue though, is that with the recommended approach, I would need to register/load all relevant plugins one at a time. Exactly like your code shows, I would create a new server, then load Postgres, APIs, etc. It's not really difficult, yet I am wondering whether it is necessary.

Except for the `authenticate` decorator, I have been able to get away with doing `const server = require('../../..');` and just looking at the environment there, as to whether to enable `pino` and such. This way, while unit tests are running logging is disabled.

Currently, I make everything into a plug and autoload from `plugins`, `routes`, `apis` directories. Importing the server, saves the need to create the server object separately and then register relevant extensions. I also feel that it is maybe more "reliable" as a test, as the test environment is "closer" to the production.

I think that maybe mocking `server.authenticate` would be better. I don't believe that decorate on the same "word" a second time would work, though.

Maybe, it could be mocked with something like:

```
    jest.mock('fastify-auth0-verify', (instance, options, done) => {
      const mockAuthenticate = jest.fn();
      instance.decorate('authenticate', mockAuthenticate);
      done();
    });
```

**Comment by simoneb** [comment]
Mocking the whole module as in your example is also a viable option, it boils down to what you want to test basically. What I'm trying to say is that there is nothing specific about this package or in general fastify plugins which requires any special patterns when it comes to mocking them, you'd just use the standard paradigms provided by your testing framework/mocking library.
