### ISSUE TITLE
Include `formatUser` from @fastify/jwt as optional parameter

### ISSUE THREAD

**Issue by fernandesGabriel** [nearform/fastify-auth0-verify#226]
Would that be interesting to have a `formatUser` optional property when registering this plugin to configure `@fastify/jwt` under the hoods? I could try to provide a PR for such.

**Comment by simoneb** [comment]
How about a more generic approach at providing any options to the underlying @fastify/jwt plugin instead?

**Comment by fernandesGabriel** [comment]
Of course @simoneb, I think that could be useful to more people, as `@fastify/jwt` has quite a few properties that at this moment can't be used while using `fastify-auth0-verrity`. I will try to come up with a PR soon then.

**Comment by taylorjames** [comment]
> Of course @simoneb, I think that could be useful to more people, as `@fastify/jwt` has quite a few properties that at this moment can't be used while using `fastify-auth0-verrity`. I will try to come up with a PR soon then.

Any updates on this? Id rather not have to fork

**Comment by taylorjames** [comment]
Submitted a PR @fernandesGabriel

**Comment by fernandesGabriel** [comment]
Hi @taylorjames Sorry for not being able to prioritize it before. Great contribution of yours.
