### ISSUE TITLE
request.jwtDecode is not a function error

### ISSUE THREAD

**Issue by bakura10** [nearform/fastify-auth0-verify#317]
Hi :),

I have been struggling with this issue for several hours, so I thought I would ask here! I am (I think) following exactly the getting started to register the plugin and validate a request:

```
import fastifyAuth0Verify from "fastify-auth0-verify";

const app = fastify({logger: true});
await app.register(fastifyAuth0Verify, {domain: 'my domain', audience: 'My audience'});

    app.get('/pong', {preValidation: app.authenticate}, async(req, reply) => {
        reply.send({message: 'ping'})
    });
```

When I don't have any JWT token, the errors make sense. However, as soon as I enter a token, I get back with the following error:

```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "request.jwtDecode is not a function"
}
```

I tried to debug by checking the library code and the various dependencies, but I can't figure out what may be happening here. It looks like if the request are not properly decorated.

Would you have an idea of what may be happening here?

Thanks! :)

**Comment by simoneb** [comment]
Can you please provide a minimal repro? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by bakura10** [comment]
Sure. Here is the complete code. It is really just that.

server.ts
```
import fastify from 'fastify';
import fastifyAuth0Verify from "fastify-auth0-verify";

(async () => {
    const app = fastify({logger: true});

    await app.register(fastifyAuth0Verify, {domain: 'dev-xxxxxx.jp.auth0.com', audience: 'http://localhost/api'});

    app.get('/pong', {onRequest: app.authenticate}, async(req, reply) => {
        reply.send({message: 'ping'})
    });

    const start = async () => {
        try {
            await app.listen({ port: 3000 });
        } catch (err) {
            app.log.error(err);
            process.exit(1);
        }
    }

    start();
})()
```

**Comment by simoneb** [comment]
Please follow the setup instructions as per the documentation. I see differences in your code which may be the reason of the problem.

**Comment by bakura10** [comment]
Sorry, I made a typo in the previous example, I'm using preValidation (not onRequest) as per the doc. I've took the guide and really can't see a single difference (beside the fact that I'm using modules, and that jwksUrl is replaced by domain as per the instructions of this package.

```
const fastify = require('fastify')
const server = fastify()

await server.register(require('fastify-jwt-jwks'), {
  jwksUrl: '<JWKS url>',
  audience: '<app audience>'
})

server.get('/verify', { preValidation: server.authenticate }, (request, reply) => {
  reply.send(request.user)
})

server.listen(0, err => {
  if (err) {
    throw err
  }
})
```

I will continue digging but I really can't spot where it is coming from :/

**Comment by simoneb** [comment]
I have simply copied your earlier script (the one using this package) into a new js file, installed fastify and fastify-auth0-verify as dependencies, and ran it, and I get exactly what I expect:

![image](https://github.com/nearform/fastify-auth0-verify/assets/20181/b6688196-d678-4ac5-9e35-e8df4d527769)

**Comment by simoneb** [comment]
If I provide a token instead, a bogus one, I also get what I expect

![image](https://github.com/nearform/fastify-auth0-verify/assets/20181/30382c2a-e566-4b29-adba-bdee69bd63b4)

**Comment by bakura10** [comment]
Yes of course :). This part works as well for me. Now try to use a JWT token with a valid format. Then you will have the error :)

**Comment by simoneb** [comment]
Ok, I have been able to reproduce the issue, which actually seems to lie in the upstream repo.

**Comment by bakura10** [comment]
Glad I’m not crazy ! I will wait for the package to be fixed thanks. Thanks a lot :)

**Comment by simoneb** [comment]
Well it would be great if you could also help figuring out where the issue is :)

**Comment by bakura10** [comment]
I will try. To be transparent I just started Node this week (coming from PHP background), and I’m fighting all day with just trying to figure out Node issues and ecosystem incompatibility. It will probably be faster for someone familiar with the code base and language, but I will check :)

**Comment by simoneb** [comment]
Welcome then. I'm confident you'll enjoy the ecosystem.

**Comment by jamesthedove** [comment]
@bakura10 have you been able to look into this?
If not, I can help pick it up.

**Comment by bakura10** [comment]
@jamesthedove i am honestly completely lost in the source code of the various dependencies. This is so much different from what I am coming from. It will probably take a few days/weeks for me to fully grasp TypeScript and how everything works. If you are familiar with it and could have a look it would be indeed very appreciated :)

**Comment by jamesthedove** [comment]
Hi @bakura10 It appears the issue is because you are testing with a token signed with a different algorithm. If you generate the token with the correct algorithm (RS256), you shouldn't get that error.
I have created a PR to provide a clearer message.

**Comment by bakura10** [comment]
Thanks, this is highly appreciated :)
