### ISSUE TITLE
Fastify-auth0-verify with Typescript

### ISSUE THREAD

**Issue by lleonori** [nearform/fastify-auth0-verify#354]
I use this plugin with Typescript, and when I register it:

```
import fastifyAuth0Verifiy from "fastify-auth0-verify";

app.register(fastifyAuth0Verifiy, {
    domain: process.env.domain,
    secret: process.env.secret,
});
```

the application still run, but typescript notify an error:
[https://pastebin.com/WeN1hbPm](url)

The export default is present inside the index.d.ts and I use it:

`export default fastifyAuth0Verify`

**Comment by ilteoood** [comment]
Can you provide a repro?

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by simoneb** [comment]
@lleonori please check https://github.com/nearform/fastify-auth0-verify/pull/355. I added (or actually, modified) a test to cover exactly your case. Unless we're doing something wrong with the types, it should work fine.

**Comment by lleonori** [comment]
@ilteoood I try to provide a repro, and it's so strange, there aren't any errors.
https://github.com/lleonori/repro-fastify-auth0

@simoneb LGTM

Maybe there are some library conflict? 
For verify this case I link my side project, if is not a problem.
https://github.com/lleonori/gymnasium-fastify

**Comment by simoneb** [comment]
Can you show us the error?

**Comment by lleonori** [comment]
import fastifyAuth0Verifiy from "fastify-auth0-verify";
 
 app.register(fastifyAuth0Verifiy, {
    // domain: process.env.DOMAIN,
    // secret: process.env.SECRET,
  });
  
this is the line and the error is [https://pastebin.com/WeN1hbPm](url)

**Comment by faizplus** [comment]
## The Problem
@lleonori This is a problem with your typescript configuration and its type compatibility with [fastify-auth0-verify](https://github.com/nearform/fastify-auth0-verify/) as you are using `"module": "NodeNext" and "moduleResolution": "NodeNext" `

https://github.com/lleonori/gymnasium-fastify/blob/1d62511bbc95b09ace1ce4f9852b1100abc5cac7/tsconfig.json#L28-L30

While [fastify-auth0-verify](https://github.com/nearform/fastify-auth0-verify/) is setup for ` "target": "es6", "module": "commonjs",`
https://github.com/nearform/fastify-auth0-verify/blob/f5f98a24775b870ae3ac8303751e07193a102d39/tsconfig.json#L3-L4

## The Solution
There are two ways that I can think of to solve this problem if I don't want to rewrite this package in `esmodule` from `commonjs`.
1. Use dynamic import inside your `async` function
    ```typescript
    import type { FastifyPluginCallback } from "fastify";
    import { FastifyAuth0VerifyOptions } from "fastify-auth0-verify";
    ...
    
    const fastifyAuth0Verifiy = (await import("fastify-auth0-verify"))
       .default as unknown as FastifyPluginCallback<FastifyAuth0VerifyOptions>;
    ```
2. Change your `tsconfig.json`'s  `module` and `moduleResolution` to
    ```json
    {
       "module": "CommonJS",
       "moduleResolution": "Node"
    }
    ```
    **Note:** 2nd option will break your code as few things will not work like `import.meta.url` and you will need to change this to their commonjs counterparts

**Comment by simoneb** [comment]
@faizplus shall our code not be compatible with a standard TS setup instead?

**Comment by faizplus** [comment]
@simoneb definitely the code should be compatible, I will try to find a way to make it work. I have provided quick solutions only.

**Comment by ilteoood** [comment]
What about using tsup to compile to both esm and cjs?
IMO it would be a good strategy to slowly making esm a first class citizen.

**Comment by simoneb** [comment]
I'm sure there must be a way to expose CJS code in a way that's usable from ESM/TS without much effort.
