### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by jsumners** [nearform/fastify-auth0-verify#5]
https://github.com/nearform/fastify-auth0-verify/blob/4d1e1f5a12825bca425ad627dfa1f5e11df438cf/index.js#L7

Does this library suffer from not handling timeouts like the web browser version (https://github.com/whatwg/fetch/issues/20)? Might it be better to use a Node native module like [`got`](https://npm.im/got)?

https://github.com/nearform/fastify-auth0-verify/blob/4d1e1f5a12825bca425ad627dfa1f5e11df438cf/README.md#L42

This `options` is not defined in the example. Shouldn't the example be copy and paste-able as-is?

**Comment by ShogunPanda** [comment]
Good point on fetch. @mcollina Any preference on that?

About the README, options is not defined as it is just sent by the fastify register interface but it is not used at all. I'll rename as _options so it's a little more clear.
