### ISSUE TITLE
FastifyDeprecation: Use onRequest hook instead

### ISSUE THREAD

**Issue by OR13** [nearform/fastify-auth0-verify#50]
```
import auth0Verify from 'fastify-auth0-verify';
server.register(auth0Verify, {
    domain: "...",
  });
```
Yields this warning:

FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: auth0Verify

Anyone following the readme and using:

```
    "fastify": "^3.2.1",
```

Might encounter this.

**Comment by OR13** [comment]
The same warning is reproduced in CI, https://github.com/nearform/fastify-auth0-verify/runs/1568329832?check_suite_focus=true#step:6:12

**Comment by treykaws** [comment]
I am also running into this warning. Just came by to report it as well.

**Comment by gjgd** [comment]
Also seeing this warning

**Comment by aspiiire** [comment]
Hey i'm also having this similar problem "[FSTDEP006] FastifyDeprecation: You are decorating Request/Reply with a reference type. This reference is shared amongst all requests. Use onRequest hook instead. Property: sessionStore"

I've tried to comment out the package but the deprecation message still shows up!

**Comment by mcollina** [comment]
I have a feeling this comment has nothing to do with this module.

**Comment by aspiiire** [comment]
> I have a feeling this comment has nothing to do with this module.

I'm sorry i'll delete it and move it in the appropriate place
