### ISSUE TITLE
npm version lag: 0.4.1 is tagged, only 0.4.0 is available

### ISSUE THREAD

**Issue by notjosh** [nearform/fastify-auth0-verify#58]
Hi!

v0.4.1 is available on [GitHub releases](https://github.com/nearform/fastify-auth0-verify/releases/tag/v0.4.1)(/git tag), but only 0.4.0 is available [via npm](https://www.npmjs.com/package/fastify-auth0-verify).

Can you please push 0.4.1 to npm? 

Thanks!

**Comment by nicolo-ribaudo** [comment]
I think that this issue can be closed, now that 0.4.1 is on npm.

**Comment by mcollina** [comment]
thanks @nicolo-ribaudo!
